language: node_js
node_js:
  - 'stable'
  - '6'
services:
  - docker
script:
  # - yarn lint
  # - yarn test
  - yarn run build --release
  - docker build -t toccoag/dashboard .
deploy:
  provider: script
  script: .travis/docker_push
  on:
    branch: docker
    node_js: stable
